import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-gray-50 text-gray-900">
          <Navbar />
          {/* Main container for page content */}
          <main className="max-w-7xl mx-auto pt-16 p-4 min-h-screen">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
